"""Add required oauth fields

Revision ID: 63a4165d4750
Revises: 4bf9e140a341
Create Date: 2025-08-25 01:24:16.757040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a4165d4750'
down_revision: Union[str, Sequence[str], None] = '4bf9e140a341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the new columns as nullable initially to avoid the NotNullViolation error.
    op.add_column('google_calendar_tokens', sa.Column('token_uri', sa.String(), nullable=True))
    op.add_column('google_calendar_tokens', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('google_calendar_tokens', sa.Column('client_secret', sa.String(), nullable=True))
    
    # Step 2: Populate the new columns for existing rows with a temporary, default value.
    # IMPORTANT: You must replace the placeholders with your actual client_id and client_secret.
    op.execute("UPDATE google_calendar_tokens SET token_uri = 'https://oauth2.googleapis.com/token'")
    op.execute("UPDATE google_calendar_tokens SET client_id = ''")
    op.execute("UPDATE google_calendar_tokens SET client_secret = ''")
    
    # Step 3: Change the columns to be NOT NULL, enforcing the constraint.
    op.alter_column('google_calendar_tokens', 'token_uri', nullable=False)
    op.alter_column('google_calendar_tokens', 'client_id', nullable=False)
    op.alter_column('google_calendar_tokens', 'client_secret', nullable=False)

    op.create_index(op.f('ix_google_calendar_tokens_user_id'), 'google_calendar_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_calendar_tokens_user_id'), table_name='google_calendar_tokens')
    op.drop_column('google_calendar_tokens', 'client_secret')
    op.drop_column('google_calendar_tokens', 'client_id')
    op.drop_column('google_calendar_tokens', 'token_uri')
    # ### end Alembic commands ###
